### ISSUE TITLE
Jackett 'all' flag still not working after last bugfix

### ISSUE THREAD

**Issue by negativzeroe** [linuxserver/docker-sonarr#131]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Jackett returns indexers with "all" flag

## Current Behavior
Jackett indexers work when copying individual indexers

## Steps to Reproduce
Create indexer with link: http://10.1.0.222:9117/torznab/all/
The rest remains the same. 

## Environment
**OS:**      Debian 10
**CPU architecture:** x86_64      
**How docker service was installed:**      docker linuxserver/radarr:latest (tested with all four tags)

## Command used to create docker container (run/create/compose/screenshot)

docker run \
    --name sonarr \
    --restart always \
    --net=local \
    -e PUID=1000 -e PGID=1001 \
    -p 8989:8989 \
    -v /etc/localtime:/etc/localtime:ro \
    -v /mnt/media/apps/config/sonarr:/config:rw \
    -v /mnt/media/tvshows:/tv:rw \
    -v /mnt/media/downloads:/downloads:rw \
    -v /mnt/media/apps/handbrake:/handbrake:rw \
    -d linuxserver/sonarr:latest  

GID 1001 exists. 

## Docker logs

```
[Error] Torznab: An error occurred while processing feed. http://10.1.0.222:9117/api/v2.0/indexers/kickasstorrent-kathow/results/torznab/api?t=tvsearch&cat=5000,5030,5040,5050,5060,5070,100118,100133,100006,100007,100041,100151,100146,100152,6000,100001,100004&extended=1&apikey=0r91bb14ffvl201adgf2uan5jaj9yhss&offset=0&limit=100&q=Flash&season=6&ep=2 

[v2.0.0.5338] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000b6] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:42 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\RssParser.cs:55 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00050] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:308 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchReleases (System.Func`2[T,TResult] pageableRequestChainSelector, System.Boolean isRecent) [0x000a0] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:143 
```

**Comment by aptalca** [comment]
This really sounds like a jackett issue rather than a docker issue. You should report it upstream to jackett

**Comment by negativzeroe** [comment]
I'll probably end up doing that tonight when I have more time to test. So far my only environment variables are that I'm using linuxserver images and didn't want to be 'that guy' posting unsupported methods of install without trying the main images first.

**Comment by Taloth** [comment]
@negativzeroe That's Jackett throwing an internal error:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417
```

My guess is that a particular result of the indexer is causing problems in Jackett. If you can still reproduce it with that exact url, then see if Jackett has logs of the actual indexer response. Then supply that information to the Jackett team via their github issue page. That should allow them to reproduce it and fix it on their end.

**Comment by negativzeroe** [comment]
@Taloth I just tested with sonarr from the official install without touching Jackett and it works with that install.

**Comment by negativzeroe** [comment]
> PS: The error log you posted is for a kickass indexer, not /all.

Oops my bad, just double checked thought it's the same error with the same lines on all. I'll check with them.
