### ISSUE TITLE
[BUG] Could not load file or assembly 'FluentMigrator.Runner.SQLite'

### ISSUE THREAD

**Issue by Klarstein** [linuxserver/docker-sonarr#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sonarr throws an epic fail since the last update and won't spin up anymore. 

### Expected Behavior

A complete startup.

### Steps To Reproduce

Config:
docker-compose

A clean install as tryout with:
`docker run -d   --name=sonarrtemp   -e PUID=1000   -e PGID=1000   -e TZ=Etc/UTC   -p 8989:8989   lscr.io/linuxserver/sonarr:latest`

Throws the same error.

### Environment

```markdown
- OS: Ubuntu server 22.04.3 LTS  
- How docker service was installed: via the Docker apt repository
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarrconfig:/config
      - /data:/media
    ports:
      - 8989:8989
```

### Container logs

```bash
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr - Version 4.0.0.748 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 


[Fatal] ConsoleApp: EPIC FAIL! 

[v4.0.0.748] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'FluentMigrator.Runner.SQLite, Version=3.3.2.9, Culture=neutral, PublicKeyToken=594eef046ac5ecb'. An internal error occurred.
 (0x8007054F)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
System.IO.FileLoadException: Could not load file or assembly 'FluentMigrator.Runner.SQLite, Version=3.3.2.9, Culture=neutral, PublicKeyToken=594eef046ac5ecb'. An internal error occurred.
 (0x8007054F)
File name: 'FluentMigrator.Runner.SQLite, Version=3.3.2.9, Culture=neutral, PublicKeyToken=594eef046ac5ecb'
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at DryIoc.Portable.<>c__DisplayClass2_0.<GetAssemblyTypesMethod>b__0(Assembly a)
   at DryIoc.Portable.GetAssemblyTypes(Assembly a)
   at DryIoc.Registrator.GetImplementationTypes(Assembly assembly)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at DryIoc.Registrator.RegisterMany(IRegistrator registrator, IEnumerable`1 implTypes, Func`2 getServiceTypes, Func`2 getImplFactory, Func`3 getServiceKey, Nullable`1 ifAlreadyRegistered)
   at DryIoc.Registrator.RegisterMany(IRegistrator registrator, IEnumerable`1 implTypes, IReuse reuse, Made made, Setup setup, Nullable`1 ifAlreadyRegistered, Func`2 serviceTypeCondition, Boolean nonPublicServiceTypes, Object serviceKey)
   at DryIoc.Registrator.RegisterMany(IRegistrator registrator, IEnumerable`1 implTypeAssemblies, Func`2 serviceTypeCondition, IReuse reuse, Made made, Setup setup, Nullable`1 ifAlreadyRegistered, Boolean nonPublicServiceTypes, Object serviceKey)
   at NzbDrone.Common.Composition.Extensions.ServiceCollectionExtensions.AutoAddServices(IContainer container, List`1 assemblyNames)
   at NzbDrone.Host.Bootstrap.<>c__DisplayClass3_0.<CreateConsoleHostBuilder>b__2(IContainer c)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass10_0`1.<ConfigureContainer>b__0(HostBuilderContext context, TContainerBuilder builder)
   at Microsoft.Extensions.Hosting.Internal.ConfigureContainerAdapter`1.ConfigureContainer(HostBuilderContext hostContext, Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback)
   at NzbDrone.Console.ConsoleApp.Main(String[] args)
```
```

**Comment by smith8ca** [comment]
Seeing the same issue on Raspbian OS (x64); Launching via docker-comopse ...

**Comment by dannytrigo** [comment]
I have the same issue. Likely an issue with sonarr rather than the lsio image

**Comment by Klarstein** [comment]
@smith8ca and @dannytrigo I was wondering if your Docker environments are setup to use namespace remapping (username-remap)?

It might explain the error, but it’s weird that before V4 everything was working _with_ the use of namespaces.
