### ISSUE TITLE
[BUG] Strange root folder issue with Sonarr

### ISSUE THREAD

**Issue by Geektasticdad** [linuxserver/docker-sonarr#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I go to Library > Library Import or Settings > Media Management and I click one of the root folders, I get the error "Unable to load root folders." 

In addition, if I try to add a new folder, the folder gets added but Sonarr also kicks back this error:

{"message":"One or more errors occurred. (Resource temporarily unavailabl)","description":"System.AggregateException: One or more errors occurred. (Resource temporarily unavailabl)\n ---> System.InvalidOperationException: Resource temporarily unavailabl\n ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].\n --- End of inner exception stack trace ---\n at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)\n at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23\n at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53\n at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 212\n at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location ---\n at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n --- End of inner exception stack trace ---\n at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n at NzbDrone.Core.RootFolders.RootFolderService.GetDetails(RootFolder rootFolder, Dictionary`2 seriesPaths, Boolean timeout) in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 213\n at NzbDrone.Core.RootFolders.RootFolderService.Add(RootFolder rootFolder) in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 119\n at Sonarr.Api.V3.RootFolders.RootFolderController.CreateRootFolder(RootFolderResource rootFolderResource) in ./Sonarr.Api.V3/RootFolders/RootFolderController.cs:line 57\n at lambda_method284(Closure , Object , Object[] )\n at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\n--- End of stack trace from previous location ---\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\n--- End of stack trace from previous location ---\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 28\n at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 41\n at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33\n at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 38\n at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 27\n at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 29\n at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"}

### Expected Behavior

I would expect it to load the root folder, specifically for Importing existing series. 

### Steps To Reproduce

1. Running Sonarr 4.0.4.1491-ls235 by linuxserver.io in docker on Ubuntu 22.04 VM on Server 2022 Hyper-V host
2. Running OpenVPN client on Ubuntu server
3. Set up ufw firewall as "kill switch" 

Not sure what else I can add here, nothing in the environment has changed, I'm hoping the error message will aid. 

### Environment

```markdown
- OS:Ubuntu 22.04
- How docker service was installed: 4.0.4.1491-ls235 by linuxserver.io
```

### CPU architecture

x86-64

### Docker creation

```bash
version: '3.3'
networks:
  pmsnet:
    ipam:
      config:
        - subnet: 10.20.30.32/28

services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      pmsnet:
        ipv4_address: 10.20.30.34
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Phoenix
    volumes:
      - sonarr_config:/config
      - /mnt/downloads:/downloads
      - /mnt/plexmedia:/mnt/plexmedia
    ports:
      - 8989:8989
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Sonarr: https://sonarr.tv/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr - Version 4.0.4.1491
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Debug] Bootstrap: Console selected
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] MigrationController: *** Migrating data source=/config/sonarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 ***
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrating
[Info] FluentMigrator.Runner.MigrationRunner: PerformDBOperation
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Performing DB Operation
[Info] DatabaseEngineVersionCheck: SQLite 3.44.2
[Info] FluentMigrator.Runner.MigrationRunner: => 0.1628398s
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrated
[Info] FluentMigrator.Runner.MigrationRunner: => 0.1726586s
[Debug] MigrationController: Took: 00:00:00.6213706
[Debug] Microsoft.Extensions.Hosting.Internal.Host: Hosting starting
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 ***
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrating
[Info] FluentMigrator.Runner.MigrationRunner: PerformDBOperation
[Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Performing DB Operation
[Info] DatabaseEngineVersionCheck: SQLite 3.44.2
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0314767s
[Info] FluentMigrator.Runner.MigrationRunner: DatabaseEngineVersionCheck migrated
[Info] FluentMigrator.Runner.MigrationRunner: => 0.0322429s
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://0.0.0.0:8989
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down.
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production
[Info] Microsoft.Hosting.Lifetime: Content root path: /app/sonarr/bin
[ls.io-init] done.
[Info] Auth: Auth-Success ip 192.168.10.46 username 'admin'
[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/Anime TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/Anime TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Info] RssSyncService: Starting RSS Sync
[Fatal] SonarrErrorPipeline: Request Failed. GET /api/v3/rootFolder/7

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Warn] Torznab: Indexer TheRARBG (Prowlarr) rss sync didn't cover the period between 03/17/2024 15:50:56 and 03/21/2024 07:32:35 UTC. Search may be required.
[Info] DownloadDecisionMaker: Processing 660 releases
[Info] RssSyncService: RSS Sync Completed. Reports found: 660, Reports grabbed: 0
[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/Anime TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/Anime TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Fatal] SonarrErrorPipeline: Request Failed. GET /api/v3/rootFolder/7

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/Anime TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/Anime TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/Anime TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

[Error] RootFolderService: Unable to get free space and unmapped folders for root folder /mnt/plexmedia/TV/

[v4.0.4.1491] System.InvalidOperationException: Resource temporarily unavailabl
 ---> Mono.Unix.UnixIOException: Resource temporarily unavailabl [EWOULDBLOCK].
   --- End of inner exception stack trace ---
   at Mono.Unix.UnixDriveInfo.Refresh(Boolean throwException)
   at Mono.Unix.UnixDriveInfo.Refresh()
   at Mono.Unix.UnixDriveInfo.get_AvailableFreeSpace()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in ./Sonarr.Mono/Disk/ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Mono/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in ./Sonarr.Core/RootFolders/RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by Geektasticdad** [comment]
If it's any consolation, I fixed this by changing the shares in the Linux host from CIFS to NFS.
